from tkinter import *
import random
from PIL import ImageTk,Image
root=Tk()
root.title("Endless Pokemon Game")
root.geometry("800x400")
root.configure(background="orange")
pikachu=ImageTk.PhotoImage(Image.open("pikachu.jpg"))
charmender=ImageTk.PhotoImage(Image.open("charmender.jpg"))
bulbasour=ImageTk.PhotoImage(Image.open("bulbasour.jpg"))
squirtle=ImageTk.PhotoImage(Image.open("squirtle.jpg"))
iyvasour=ImageTk.PhotoImage(Image.open("Iyvasour.jpg"))
ratata=ImageTk.PhotoImage(Image.open("ratata.jpg"))
paras=ImageTk.PhotoImage(Image.open("paras.jpg"))
meowth=ImageTk.PhotoImage(Image.open("meowth.jpg"))
nidoking=ImageTk.PhotoImage(Image.open("nidoking.jpg"))
kadabra=ImageTk.PhotoImage(Image.open("kadabra.jpg"))
jigglypuff=ImageTk.PhotoImage(Image.open("jigglypuff.jpg"))
persion=ImageTk.PhotoImage(Image.open("persion.jpg"))
abra=ImageTk.PhotoImage(Image.open("abra.jpg"))
label1=Label(root,bg="red",fg="white",text="Player1")
label1.place(relx=0.1,rely=0.3,anchor=CENTER)
label2=Label(root,bg="red",fg="white",text="Player2")
label2.place(relx=0.9,rely=0.3,anchor=CENTER)
labelp1=Label(root,bg="red",fg="white")
labelp1.place(relx=0.1,rely=0.4,anchor=CENTER)
labelp2=Label(root,bg="red",fg="white")
labelp2.place(relx=0.9,rely=0.3,anchor=CENTER)
labelpoke=Label(root,bg="red",fg="white")
labelpoke.place(relx=0.5,rely=0.5,anchor=CENTER)
root.mainloop()